[mypy]
python_version = 3.7
check_untyped_defs = True
show_error_codes = True
;disable_error_code=union-attr
disable_error_code = import-not-found
exclude = (?x)(
          ^yk_gmd_blender/blender/
          )